removendo forceCoversAnnotation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,8 +27,17 @@ jobs:
     - name: Install dependencies
       run: composer install --prefer-dist --no-progress --no-suggest
 
+    - name: Run unit tests with coverage
+      run: vendor/bin/phpunit --coverage-clover=coverage.xml
+
     - name: Run BDD tests
       run: vendor/bin/behat
+
+    - name: Upload coverage to Codecov
+      uses: codecov/codecov-action@v3
+      with:
+        file: ./coverage.xml
+        fail_ci_if_error: true
 
     - name: SonarCloud Scan
       uses: SonarSource/sonarcloud-github-action@master
@@ -43,3 +52,16 @@ jobs:
           -Dsonar.tests=tests
           -Dsonar.php.coverage.reportPaths=coverage.xml
           -Dsonar.php.tests.reportPath=test-report.xml
+
+    - name: Check code coverage
+      run: |
+        if [ ! -f coverage.xml ]; then
+          echo "coverage.xml file not found!"
+          exit 1
+        fi
+        COVERAGE=$(grep -Po '(?<=<coverage generated=".*" line-rate=").*?(?=")' coverage.xml)
+        COVERAGE_PERCENTAGE=$(echo "$COVERAGE * 100" | bc)
+        if (( $(echo "$COVERAGE_PERCENTAGE < 80" | bc -l) )); then
+          echo "Code coverage is below 80%"
+          exit 1
+        fi
